name: ui_ecommerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2
environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  motion_tab_bar_v2: ^0.3.0
  dots_indicator: ^3.0.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  dart_jsonwebtoken: ^2.13.0
  loading_animation_widget: ^1.2.1
  font_awesome_flutter: ^10.7.0
  dropdown_button2: ^2.3.9
  easy_autocomplete: ^1.6.0
  animated_bottom_navigation_bar: ^1.3.3
  curved_labeled_navigation_bar: ^2.0.2
  photo_view: ^0.15.0
  flutter_spinkit: ^5.2.1
  textfield_search: ^0.10.0
  url_launcher: ^6.2.6
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  badges: ^3.1.2
  flutter_notification_manager: ^1.0.0
  flutter_app_badger: ^1.5.0
  flutter_dialogs: ^3.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appcbc.jpg"
  image_path_ios: "assets/images/appcbc.jpg"

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal.ttf
